# Generated by Django 4.1.5 on 2023-01-31 06:59

from django.db import migrations
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', userapp.models.CustomUserManager()),
            ],
        ),
    ]
