# Generated by Django 4.1.5 on 2023-01-31 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='Username', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')], verbose_name='User_name'),
        ),
    ]
