# Generated by Django 4.1.5 on 2023-01-31 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')], verbose_name='User_name'),
        ),
    ]
